<?php

namespace Devoir;

$_DEVOIR_CONFIG = [
	'APPLICATION_NAMESPACE' => APPLICATION_NAMESPACE,
	'CONTROLLERS_NAMESPACE' => CONTROLLERS_NAMESPACE,
	'MODELS_NAMESPACE' => MODELS_NAMESPACE,
	'VIEWS_NAMESPACE' => VIEWS_NAMESPACE,
	'IS_DEBUG' => IS_DEBUG,
	'DEFAULT_CONTROLLER' => DEFAULT_CONTROLLER,
	'DEFAULT_ACTION' => DEFAULT_ACTION,
];
